global_costmap:
  global_frame: map
  robot_base_frame: /om_with_tb3/base_footprint
  scan:
    topic: /om_with_tb3/scan_filtered
    sensor_frame: /om_with_tb3/base_scan

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
 
