local_costmap:
  global_frame: om_with_tb3/odom
  robot_base_frame: om_with_tb3/base_footprint
  scan:
    topic: /om_with_tb3/scan_filtered
    sensor_frame: /om_with_tb3/base_scan

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  
