controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_mobile_controller
    joints:
      - virtual_joint
      - wheel_left_joint
      - wheel_right_joint