controller_names:
  - arm_controller
  - gripper_controller

arm_controller:
  type: FollowJointTrajectory #joint_trajectory_controller/JointTrajectoryController
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
    - joint4


gripper_controller:
  type: GripperCommand
  action_ns: gripper_cmd
  default: true
  joints:
    - gripper_left_joint
    - gripper_right_joint
